/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSplatRouteImport } from './routes/workspace.$'
import { Route as SettingsFileRouteImport } from './routes/settings.$file'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSplatRoute = WorkspaceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SettingsFileRoute = SettingsFileRouteImport.update({
  id: '/$file',
  path: '/$file',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/settings/$file': typeof SettingsFileRoute
  '/workspace/$': typeof WorkspaceSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/settings/$file': typeof SettingsFileRoute
  '/workspace/$': typeof WorkspaceSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/settings/$file': typeof SettingsFileRoute
  '/workspace/$': typeof WorkspaceSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/workspace'
    | '/settings/$file'
    | '/workspace/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/workspace' | '/settings/$file' | '/workspace/$'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/workspace'
    | '/settings/$file'
    | '/workspace/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$': {
      id: '/workspace/$'
      path: '/$'
      fullPath: '/workspace/$'
      preLoaderRoute: typeof WorkspaceSplatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/settings/$file': {
      id: '/settings/$file'
      path: '/$file'
      fullPath: '/settings/$file'
      preLoaderRoute: typeof SettingsFileRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsFileRoute: typeof SettingsFileRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsFileRoute: SettingsFileRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceSplatRoute: typeof WorkspaceSplatRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSplatRoute: WorkspaceSplatRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
