/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsArchivedAgentsRouteImport } from './routes/settings.archived-agents'
import { Route as AgentSlugIndexRouteImport } from './routes/agent.$slug.index'
import { Route as AgentSlugWorkspaceIndexRouteImport } from './routes/agent.$slug.workspace.index'
import { Route as AgentSlugSkillsIndexRouteImport } from './routes/agent.$slug.skills.index'
import { Route as AgentSlugMcpIndexRouteImport } from './routes/agent.$slug.mcp.index'
import { Route as AgentSlugIdentityIndexRouteImport } from './routes/agent.$slug.identity.index'
import { Route as AgentSlugBackgroundTasksIndexRouteImport } from './routes/agent.$slug.background-tasks.index'
import { Route as AgentSlugWorkspaceSplatRouteImport } from './routes/agent.$slug.workspace.$'
import { Route as AgentSlugIdentityFileRouteImport } from './routes/agent.$slug.identity.$file'
import { Route as AgentSlugBackgroundTasksTaskIdRouteImport } from './routes/agent.$slug.background-tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsArchivedAgentsRoute = SettingsArchivedAgentsRouteImport.update({
  id: '/settings/archived-agents',
  path: '/settings/archived-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugIndexRoute = AgentSlugIndexRouteImport.update({
  id: '/agent/$slug/',
  path: '/agent/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugWorkspaceIndexRoute = AgentSlugWorkspaceIndexRouteImport.update({
  id: '/agent/$slug/workspace/',
  path: '/agent/$slug/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugSkillsIndexRoute = AgentSlugSkillsIndexRouteImport.update({
  id: '/agent/$slug/skills/',
  path: '/agent/$slug/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugMcpIndexRoute = AgentSlugMcpIndexRouteImport.update({
  id: '/agent/$slug/mcp/',
  path: '/agent/$slug/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugIdentityIndexRoute = AgentSlugIdentityIndexRouteImport.update({
  id: '/agent/$slug/identity/',
  path: '/agent/$slug/identity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugBackgroundTasksIndexRoute =
  AgentSlugBackgroundTasksIndexRouteImport.update({
    id: '/agent/$slug/background-tasks/',
    path: '/agent/$slug/background-tasks/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentSlugWorkspaceSplatRoute = AgentSlugWorkspaceSplatRouteImport.update({
  id: '/agent/$slug/workspace/$',
  path: '/agent/$slug/workspace/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugIdentityFileRoute = AgentSlugIdentityFileRouteImport.update({
  id: '/agent/$slug/identity/$file',
  path: '/agent/$slug/identity/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugBackgroundTasksTaskIdRoute =
  AgentSlugBackgroundTasksTaskIdRouteImport.update({
    id: '/agent/$slug/background-tasks/$taskId',
    path: '/agent/$slug/background-tasks/$taskId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/archived-agents': typeof SettingsArchivedAgentsRoute
  '/settings/': typeof SettingsIndexRoute
  '/agent/$slug/': typeof AgentSlugIndexRoute
  '/agent/$slug/background-tasks/$taskId': typeof AgentSlugBackgroundTasksTaskIdRoute
  '/agent/$slug/identity/$file': typeof AgentSlugIdentityFileRoute
  '/agent/$slug/workspace/$': typeof AgentSlugWorkspaceSplatRoute
  '/agent/$slug/background-tasks/': typeof AgentSlugBackgroundTasksIndexRoute
  '/agent/$slug/identity/': typeof AgentSlugIdentityIndexRoute
  '/agent/$slug/mcp/': typeof AgentSlugMcpIndexRoute
  '/agent/$slug/skills/': typeof AgentSlugSkillsIndexRoute
  '/agent/$slug/workspace/': typeof AgentSlugWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/archived-agents': typeof SettingsArchivedAgentsRoute
  '/settings': typeof SettingsIndexRoute
  '/agent/$slug': typeof AgentSlugIndexRoute
  '/agent/$slug/background-tasks/$taskId': typeof AgentSlugBackgroundTasksTaskIdRoute
  '/agent/$slug/identity/$file': typeof AgentSlugIdentityFileRoute
  '/agent/$slug/workspace/$': typeof AgentSlugWorkspaceSplatRoute
  '/agent/$slug/background-tasks': typeof AgentSlugBackgroundTasksIndexRoute
  '/agent/$slug/identity': typeof AgentSlugIdentityIndexRoute
  '/agent/$slug/mcp': typeof AgentSlugMcpIndexRoute
  '/agent/$slug/skills': typeof AgentSlugSkillsIndexRoute
  '/agent/$slug/workspace': typeof AgentSlugWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/archived-agents': typeof SettingsArchivedAgentsRoute
  '/settings/': typeof SettingsIndexRoute
  '/agent/$slug/': typeof AgentSlugIndexRoute
  '/agent/$slug/background-tasks/$taskId': typeof AgentSlugBackgroundTasksTaskIdRoute
  '/agent/$slug/identity/$file': typeof AgentSlugIdentityFileRoute
  '/agent/$slug/workspace/$': typeof AgentSlugWorkspaceSplatRoute
  '/agent/$slug/background-tasks/': typeof AgentSlugBackgroundTasksIndexRoute
  '/agent/$slug/identity/': typeof AgentSlugIdentityIndexRoute
  '/agent/$slug/mcp/': typeof AgentSlugMcpIndexRoute
  '/agent/$slug/skills/': typeof AgentSlugSkillsIndexRoute
  '/agent/$slug/workspace/': typeof AgentSlugWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/archived-agents'
    | '/settings/'
    | '/agent/$slug/'
    | '/agent/$slug/background-tasks/$taskId'
    | '/agent/$slug/identity/$file'
    | '/agent/$slug/workspace/$'
    | '/agent/$slug/background-tasks/'
    | '/agent/$slug/identity/'
    | '/agent/$slug/mcp/'
    | '/agent/$slug/skills/'
    | '/agent/$slug/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/archived-agents'
    | '/settings'
    | '/agent/$slug'
    | '/agent/$slug/background-tasks/$taskId'
    | '/agent/$slug/identity/$file'
    | '/agent/$slug/workspace/$'
    | '/agent/$slug/background-tasks'
    | '/agent/$slug/identity'
    | '/agent/$slug/mcp'
    | '/agent/$slug/skills'
    | '/agent/$slug/workspace'
  id:
    | '__root__'
    | '/'
    | '/settings/archived-agents'
    | '/settings/'
    | '/agent/$slug/'
    | '/agent/$slug/background-tasks/$taskId'
    | '/agent/$slug/identity/$file'
    | '/agent/$slug/workspace/$'
    | '/agent/$slug/background-tasks/'
    | '/agent/$slug/identity/'
    | '/agent/$slug/mcp/'
    | '/agent/$slug/skills/'
    | '/agent/$slug/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsArchivedAgentsRoute: typeof SettingsArchivedAgentsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AgentSlugIndexRoute: typeof AgentSlugIndexRoute
  AgentSlugBackgroundTasksTaskIdRoute: typeof AgentSlugBackgroundTasksTaskIdRoute
  AgentSlugIdentityFileRoute: typeof AgentSlugIdentityFileRoute
  AgentSlugWorkspaceSplatRoute: typeof AgentSlugWorkspaceSplatRoute
  AgentSlugBackgroundTasksIndexRoute: typeof AgentSlugBackgroundTasksIndexRoute
  AgentSlugIdentityIndexRoute: typeof AgentSlugIdentityIndexRoute
  AgentSlugMcpIndexRoute: typeof AgentSlugMcpIndexRoute
  AgentSlugSkillsIndexRoute: typeof AgentSlugSkillsIndexRoute
  AgentSlugWorkspaceIndexRoute: typeof AgentSlugWorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/archived-agents': {
      id: '/settings/archived-agents'
      path: '/settings/archived-agents'
      fullPath: '/settings/archived-agents'
      preLoaderRoute: typeof SettingsArchivedAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/': {
      id: '/agent/$slug/'
      path: '/agent/$slug'
      fullPath: '/agent/$slug/'
      preLoaderRoute: typeof AgentSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/workspace/': {
      id: '/agent/$slug/workspace/'
      path: '/agent/$slug/workspace'
      fullPath: '/agent/$slug/workspace/'
      preLoaderRoute: typeof AgentSlugWorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/skills/': {
      id: '/agent/$slug/skills/'
      path: '/agent/$slug/skills'
      fullPath: '/agent/$slug/skills/'
      preLoaderRoute: typeof AgentSlugSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/mcp/': {
      id: '/agent/$slug/mcp/'
      path: '/agent/$slug/mcp'
      fullPath: '/agent/$slug/mcp/'
      preLoaderRoute: typeof AgentSlugMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/identity/': {
      id: '/agent/$slug/identity/'
      path: '/agent/$slug/identity'
      fullPath: '/agent/$slug/identity/'
      preLoaderRoute: typeof AgentSlugIdentityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/background-tasks/': {
      id: '/agent/$slug/background-tasks/'
      path: '/agent/$slug/background-tasks'
      fullPath: '/agent/$slug/background-tasks/'
      preLoaderRoute: typeof AgentSlugBackgroundTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/workspace/$': {
      id: '/agent/$slug/workspace/$'
      path: '/agent/$slug/workspace/$'
      fullPath: '/agent/$slug/workspace/$'
      preLoaderRoute: typeof AgentSlugWorkspaceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/identity/$file': {
      id: '/agent/$slug/identity/$file'
      path: '/agent/$slug/identity/$file'
      fullPath: '/agent/$slug/identity/$file'
      preLoaderRoute: typeof AgentSlugIdentityFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug/background-tasks/$taskId': {
      id: '/agent/$slug/background-tasks/$taskId'
      path: '/agent/$slug/background-tasks/$taskId'
      fullPath: '/agent/$slug/background-tasks/$taskId'
      preLoaderRoute: typeof AgentSlugBackgroundTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsArchivedAgentsRoute: SettingsArchivedAgentsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AgentSlugIndexRoute: AgentSlugIndexRoute,
  AgentSlugBackgroundTasksTaskIdRoute: AgentSlugBackgroundTasksTaskIdRoute,
  AgentSlugIdentityFileRoute: AgentSlugIdentityFileRoute,
  AgentSlugWorkspaceSplatRoute: AgentSlugWorkspaceSplatRoute,
  AgentSlugBackgroundTasksIndexRoute: AgentSlugBackgroundTasksIndexRoute,
  AgentSlugIdentityIndexRoute: AgentSlugIdentityIndexRoute,
  AgentSlugMcpIndexRoute: AgentSlugMcpIndexRoute,
  AgentSlugSkillsIndexRoute: AgentSlugSkillsIndexRoute,
  AgentSlugWorkspaceIndexRoute: AgentSlugWorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
