/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as WorkspaceSplatRouteImport } from './routes/workspace.$'
import { Route as SettingsFileRouteImport } from './routes/settings.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSplatRoute = WorkspaceSplatRouteImport.update({
  id: '/workspace/$',
  path: '/workspace/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFileRoute = SettingsFileRouteImport.update({
  id: '/settings/$file',
  path: '/settings/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/$file': typeof SettingsFileRoute
  '/workspace/$': typeof WorkspaceSplatRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/$file': typeof SettingsFileRoute
  '/workspace/$': typeof WorkspaceSplatRoute
  '/settings': typeof SettingsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/$file': typeof SettingsFileRoute
  '/workspace/$': typeof WorkspaceSplatRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/$file'
    | '/workspace/$'
    | '/settings/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/$file' | '/workspace/$' | '/settings' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/settings/$file'
    | '/workspace/$'
    | '/settings/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsFileRoute: typeof SettingsFileRoute
  WorkspaceSplatRoute: typeof WorkspaceSplatRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$': {
      id: '/workspace/$'
      path: '/workspace/$'
      fullPath: '/workspace/$'
      preLoaderRoute: typeof WorkspaceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$file': {
      id: '/settings/$file'
      path: '/settings/$file'
      fullPath: '/settings/$file'
      preLoaderRoute: typeof SettingsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsFileRoute: SettingsFileRoute,
  WorkspaceSplatRoute: WorkspaceSplatRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
